# Dockerfile para o backend Node.js
FROM node:18

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos package.json e package-lock.json
COPY server/package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código
COPY server/ .

# Exponha a porta usada pelo servidor Node.js
EXPOSE 3333

# Inicie o servidor Node.js
CMD ["npm", "start"]
